// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaNCHXFTwctIbtyA9gC8uVN6S7kTjxZ68',
    appId: '1:924196458076:web:84424646802a319f292099',
    messagingSenderId: '924196458076',
    projectId: 'proyecto2-3a060',
    authDomain: 'proyecto2-3a060.firebaseapp.com',
    storageBucket: 'proyecto2-3a060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRoPDwDpasO2CWkiNg-nXWBiUGHx-tcI',
    appId: '1:924196458076:android:91d90cf145266e34292099',
    messagingSenderId: '924196458076',
    projectId: 'proyecto2-3a060',
    storageBucket: 'proyecto2-3a060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkwvcIg74t4cHx0c-zeuqVY2Sz7BYlMgk',
    appId: '1:924196458076:ios:600c83f4d5481baf292099',
    messagingSenderId: '924196458076',
    projectId: 'proyecto2-3a060',
    storageBucket: 'proyecto2-3a060.appspot.com',
    iosClientId: '924196458076-djf859h0lbhf0vc997rdccsuaclj7ta6.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto219400594',
  );
}
